### PR TITLE
Add Garena client support

### PR DESCRIPTION
**Pull request by borndead**

### CODE REVIEW

**Comment by xyzz** [comment]
why did you change a lot of std::string into QString?

**Comment by borndead** [comment]
cause std::string bad for UTF8 strings

**Comment by xyzz** [comment]
Really, what's the problem? While it's true std::string doesn't have any encoding support at all we don't rely on it anywhere.

I want to say if you are going to make such big changes it's always better to discuss them beforehand. In its current state this pull request won't be merged. However if you revert the std::string/QString change and also revert the change in which you updated rapidjson and removed sqlite (because it makes very hard to review such pull), I will consider merging the changes.

**Comment by borndead** [comment]
Garena have its own poe portal and all responces coded with utf. I mean its really better rewrite all app to unicode, then somehow convert responces to ansi chars. especially user profile name can contain non ansi chars in name like "C:\Users\Все пользователи" and with std::string i cant event create app data directories.
sqlite was removed to rewrite datamanager class to QT native sqlite support.

**Comment by borndead** [comment]
also its better remove rapidjson and use internal QT json support

**Pull request closed without merging**
