### PR TITLE
Fixed test includes for visual studio.

### PR DESCRIPTION
**Pull request by krab**
Quotes in #include means you specify absolute path. For relative path need to use <>. GNU Make dont care about it. But visual studio have problems with it.

### CODE REVIEW

**Comment by xyzz** [comment]
What VS version does the issue affect?

**Comment by krab** [comment]
I mean nmake not vs. Builded from QtCreator 3.2.2, Qt 5.4 and nmake from VS2013.

**Comment by xyzz** [comment]
Okay but what about commit a340988afb94a137662ca2a93f6fb3c367a290fd? It generates a lot of warnings https://ci.appveyor.com/project/xyzz/acquisition/build/1.0.30

**Comment by krab** [comment]
Interesting. qmake.exe -tp vc added definition Q_COMPILER_INITIALIZER_LISTS by default. But QtCreator cant do that.

 Anyway i can add this define manual in qmake project. Dont merge that commit a340988 :)

**Comment by xyzz** [comment]
ok merged a85f826891c916d4c7971e8d2805c47fb42885a4

**Pull request closed without merging**
