### PR TITLE
Tab selection and caching enhancements

### PR DESCRIPTION
**Pull request by ericsium**
This pull request is mainly for a code review and to get feeback on the proposed new web caching and tab selection features.  I'll be happy to fix anything that doesn't fit in with your coding methodology.

Details of the changes are in the individual commits.

Just want to call out the few features not yet implemented here - these are minor but wanted to send the pull request before the weekend.

Still to be implemented:
- checked state is not yet saved to database
- Need to update throttling logic as many tabs will be retrieved from
cache and we don't want those to count against throttling limit such
that we get throttled early.

### CODE REVIEW

**Comment by xyzz** [comment]
Hi, I'm on vacation now, so I think I'll only be able to review this pull request on ~5th feb, sorry.

**Comment by ericsium** [comment]
Ok, well that gave me time to resolve the two major issues I know about and do some cleanup.  I've done some testing in my standard account with 90 tabs and everything seems to be working as intended so far...

Some thoughts/questions on a few details.  I initially started thinking about this/implementing when Chris mentioned the servers were having issues handling tab requests so was trying to minimize the load and give users more options for tab loading.

1. By default currently any 'new' tabs (either first time loaded, name change, tab added) will by default be *unchecked*.  Having them *checked* by default would be similar to existing behavior where we tend to load everything by default but might result in more unnecessary tab requests.  Wondering if you have a preference here. Any tabs which have existing buyouts entered will always be 'force checked'.

2. I'm a little unsure of whether it's best to use GetUniqueHash or GetHeader to track checked tabs.  GetUniqueHash allows maintaining state when users move tabs, but will apply to all tabs with same name.  GetHeader doesn't have same-name problem but will lose state if tabs are moved.  I'm currently going with GetUniqueHash as I think users are not as likely to have multiple tabs with the same name and might more often move tabs.

**Comment by Gloorf** [comment]
1. I think new tabs should be checked by default ; it just makes more sense. A decent amount of people use acquisition because it's easy to use out of the box, having to manually check the tabs doesn't go in this direction.

2. I guess it depends on the people, i know that i move my tabs more often than i rename my tabs, but maybe it's just me

**Comment by ericsium** [comment]
Yeah, I think I agree with you on #1, probably best to leave default behavior the same and let users choose to deselect tabs they don't want to refresh.

**Comment by ericsium** [comment]
Another few comments, we could have a menu option to basically enable/disable this whole feature.  So, for example it would hide all the checkboxes from the user if they didn't enable the selective caching feature.

I've also coded things to be ready for multi-selection.  There is two places this might be useful, one is for selecting and then pricing a number of items at the same time, the other is to select a number of items and then right click to check or uncheck all selected tabs.

**Comment by xyzz** [comment]
1. I think all tabs should be checked by default
2. `GetUniqueHash` is fine

Some bugs I've found (without looking at the code yet):

* When the checkbox is clicked the treeview should be updated immediately so that when there are multiple tabs with same name the user sees that checking one of them changes the state of the other tabs.
* The refresh status (in the bottom left corner) is wrong: it should display the checked number of tabs as the total. It also displays the "throttled" message while it's not actually getting throttled.
* If I set an item/tab buyout the check mark changes to a square (on Windows at least). Then if it's set back to "ignore" the square doesn't disappear, and it works in a weird way with tabs that aren't checked.

By the way, should we include items from unchecked tabs into the shop? I don't think there's a use case where this would be useful -- you usually want to generate your shop using items in tabs that are actually updated. Otherwise there could also be issues when you set an item buyout, uncheck the tab, move the item somewhere else, now the shop won't generate. It's better not to include items from unchecked tabs at all I think.

**Comment by ericsium** [comment]
This is from one of my checkin messages and explains the checkbox 'square' thing.  Your last paragraph basically describes exactly why I implemented it this way.

- checkboxes are 'forced' and made a sold color if a tab contains any
buyouts.  This is partially to maintain integrity when shop data is
updated.  Partly to indicate to users what tabs contain any buyouts and
party because I think it's (arguably) what users generally want to have
happen.

The 'checked' state and 'forced' state is maintained separately.  If you remove all buyouts it will revert to last checked state.

It would be worth considering here whether we should 'force' a refresh if user 'manually' requests a shop update.  That would pretty much guarentee the integrity of the shop data.


Regarding the refresh status.  It is not technically wrong given the implementation - all tabs are always 'reloaded' from the perspective of the tool, it's just that tabs which are 'checked' have an opportunity to 'hit' in the cache (they may or may not, if they dont' have a cache entry they are fetched normally) and therefore they appear to just be fetched really quickly.  I tried to make minimal changes to existing code and tried to leverage existing code paths. Once you look at the code this might make more sense, let me know if you still think something needs adjustment here.


I'll fix the treeview update issue and change things so that all tabs are checked by default.

**Comment by ericsium** [comment]
Oh, yes, BTW I see the bug you're talking about where when you set buyout tab back to ignore it's not clearing the 'forced' state.  Will fix that.

**Comment by ericsium** [comment]
Made a bunch of updates, see checkin messages for details.

I only see one issue right now - currently 'empty' tabs are not listed, nor are they do they have an associated bucket or location.  The problem is that the user doesn't have an opportunity to uncheck these tabs so they are always loaded from the server.  This can make the cached statistics a bit confusing to follow.

I think now that we have cache-control per tab we may want to list empty tabs.

**Comment by xyzz** [comment]
Okay, sure, displaying empty tabs is fine.

**Comment by ericsium** [comment]
This branch is now feature complete - not planning to add anything else here other than bugfixes or changes due to code reviews.  Multi-selection and display of empty tabs was enabled in the previous few checkins. Details in checkin messages.

Only currently open issue I know about is that the auto-shop refresh stuff needs to be updated to make sense with new refresh options, otherwise in bug-hunting phase.

**Comment by ericsium** [comment]
I fixed the issue with shop updating without good reason.  I think it was actually an existing bug which probably will fix #223.

I haven't found any other issues with this branch.

**Pull request merged**
