### PR TITLE
Auto online fix for new 64 exe

### PR DESCRIPTION
**Pull request by ericsium**

### CODE REVIEW

**Comment by ericsium** [comment]
resolves #362

**Comment by guyfrozen** [comment]
Where does this code need to go?????

**Comment by ericsium** [comment]
This fix will be included in the next release.  xyz manages the releases so not sure when he will get to it.

**Comment by Tomeqf** [comment]
While waiting for devs to update acquisition to detect PathofExile_x64.exe task (Dx11 version), just open DX9 version of PoE and leave it in login menu, mute, minimize, and go play on Dx11 version. Leaving D9 version in login menu is enough for acquisition to update status, as it simply searches for Pathofexile.exe task being run.

**Pull request merged**
