### PR TITLE
Initial handling for ascendency in-game pricing

### PR DESCRIPTION
**Pull request by ericsium**
This is a 'beta' pull, ready for review/input as main content is here.  Still needs debugging and a bit more work but wanted to push out tonight.

Recognize in-game tab pricing and prevent users from being able to
modify tabs priced in game.

Properly propagate in-game tab prices etc... so it's easy for users to
see what is priced and what the values are for all items whether in-game
or out of game pricing is used.

Prevent in-game pricing data from being saved or posted to forumns.

Not yet implemented:
Handling of item pricing from 'note' field.
Still need to do a lot of verification/bug hunting.
May want to actually save in-game pricing to allow last modified records
to be kept

### CODE REVIEW

**Comment by xyzz** [comment]
clang build is failing on travis, can you fix it?

**Comment by ericsium** [comment]
Yeah, noticed last night but too tired to fix.  Will send fix shortly.

**Comment by ericsium** [comment]
xyz, is there any reason that travis needs to use GCC 4.8 instead of GCC 4.9.2 used by QT compiler?  The problem is that the <regexp> library is hopelessly broken in GCC 4.8 and not fixed until GCC 4.9.  You'll notice the test suite does not fail if tested locally.

Options are to either update the compiler used by Travis or I can change to use QT's regular expression library QRegularExpression.

**Comment by xyzz** [comment]
Yeah, upgrading travis compiler is fine, feel free to do that in this same pull request.

**Comment by ericsium** [comment]
Will be attempting changes in line with:

http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

**Comment by ericsium** [comment]
I think this branch is pretty solid now, I did a few hours of verif/bug hunting and don't know of any current major issues.

Summary:
 - Seamlessly integrate in-game tab pricing with out-of-game tab pricing
 - Display in-game pricing (tabs and items) but don't allow users to modify these prices
 - Only send items to forums that are priced out-of-game
 - It's possible to have individual items in a tab priced both out-of-game and in-game
 - Track last modified attributes for all in-game items from the point at which the pricing is observed
 - Prices made in game will override out-of-game pricing on next refresh if both are specified

**Comment by xyzz** [comment]
Ok, merged.

PS: You've made quite a lot of useful contributions, so would you be fine with me adding you as a contributor to this project?

**Comment by ericsium** [comment]
Yeah, definitely - thanks!  I love C++ and this project has been a great way for me to get experience with a lot of other things I wanted to learn more about - qt/github/travis etc...  It's all pretty slick.

**Comment by xyzz** [comment]
Great! I've added you now. By the way, is there an easy way to get in touch? Perhaps you could join #pathofexile-dev on freenode (or maybe we should pick a different channel?)

**Comment by ericsium** [comment]
I haven't used IRC much at all but can try it.  We could use #acquisition-dev if needed I suppose.

**Pull request merged**
