### PR TITLE
Proposed fix for issues #174 and #16

### PR DESCRIPTION
**Pull request by ericsium**
Tab expansion behavior is now based on search field state.

1. If no search fields are populated the expansion states for tab items
are now persistent.

2. If search fields are populated all tabs are automatically expanded
and there continues to be no persistent memory for expansion states.

3. On transition from search field populated -> not populated the last
saved expansion state is restored (before search terms were entered).

### CODE REVIEW

**Comment by xyzz** [comment]
Thanks for the pull request.

> If search fields are populated all tabs are automatically expanded

It seems that's not what your code does, it also checks `if (current_search_->items().size() <= MAX_EXPANDABLE_ITEMS)`. Maybe this should be removed completely? Not sure if it could create any performance issues though.

Also with your changes when switching search tabs the expansion state is preserved -- which is good -- unless there's a filter active.

**Comment by ericsium** [comment]
That's true, I didn't remove the check against MAX_EXPANDABLE_ITEMS yet, wasn't sure if you had some other reason for that - but I can't see any good reason not to.

That's right, expansion state is only preserved if any filters are active.  I think that that users would normally want full expansion once they start adding constraints to see all items matchining their contraint.

**Comment by ericsium** [comment]
Removed check for MAX_EXPANDABLE_ITEMS on branch, if any performance issues come up we can consider reverting this.

**Comment by Novynn** [comment]
Looks kind of similar to the approach I took in Acquisition Plus. There aren't any real performance issues as far as I can tell with an implementation such as this.

Just my 2c.

**Pull request merged**
