### PR TITLE
Add currency vaal orb

### PR DESCRIPTION
**Pull request by joshmachol**
Is this sufficient? Please let me know if there is anything else that would need to be done.

### CODE REVIEW

**Comment by xyzz** [comment]
Thanks, however the issue here is that poe.trade doesn't support vaal orbs yet, this should be fixed soon.

**Comment by joshmachol** [comment]
Okay, that's good to know. Once poe.trade supports vaal orbs, would there need to be any additional changes to acquisition that this pull doesn't cover?

**Comment by conetopia** [comment]
vaal / armour scraps / whetstones / scrolls id/tp
would like to have added for the hell of it.

**Comment by GrappigPanda** [comment]
Vaal orbs are supported on poe.trade now, it seems.

**Pull request merged**
